app:
  eureka-server: localhost
  eureka-username: username
  eureka-password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

# health check
management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: "*"

# tracing
management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
management.tracing.sampling.probability: 1.0
# include service name, trace id, span id in log output
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"



