server:
  port: 8001

flyway:
  user: postgres
  password: postgres
  locations: filesystem:db/migration
  schema: products

spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/products?currentSchema=products
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    function:
      definition: messageProcessor
    stream:
      default:
        contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
        default:
          consumer:
            autoRebalanceEnabled: true
        bindings:
          messageProcessor-in-0:
            consumer:
              enableDlq: true
              dlqName: product-dlq-topic
      bindings:
        messageProcessor-in-0:
          destination: product-topic
          group: product-group
          consumer:
            # retry
            maxAttempts: 1
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0