server.port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:${user.dir}/../../config-repo
  application:
    name: config-server
  security:
    user:
      name: dev-usr
      password: dev-pwd

app:
  eureka-server: localhost
  eureka-username: username
  eureka-password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: health