spring.config.import: "optional:configserver:"
spring:
  application.name: product
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://localhost:8888
    username: dev-usr
    password: dev-pwd

logging:
  level:
    root: INFO
    com.example: INFO