server:
  port: 8003

flyway:
  user: postgres
  password: postgres
  locations: filesystem:db/migration
  schema: reviews

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reviews?currentSchema=reviews
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect